# Permalinks
permalink:        pretty

# Setup
title:            Phil Wright
tagline:          
url:              phirlot.github.io
paginate:         1
baseurl:          /
author:
  name:           Phil Wright
  url:            phirlot.github.io
  email:          
twitter:          phirlot
description:      Gamer. YouTuber. Role model? Sex symbol.
markdown:         kramdown
kramdown:
  input:          GFM
  smart_quotes:   ["lsquo", "rsquo", "ldquo", "rdquo"]

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/phirlot/phirlot.github.io


# Ruby gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
